apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zrv0k9r1s-go 
  janus-idp.io/tekton: zrv0k9r1s-go
  backstage.io/kubernetes-id: zrv0k9r1s-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zrv0k9r1s-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml