apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zrv0k9r1s-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zrv0k9r1s-go 
  name: zrv0k9r1s-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zrv0k9r1s-go 
